apiVersion: batch/v1
kind: Job
metadata:
  name: build-test-image
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 2400 # time to allow job to run
  template:
    metadata:
      labels:
        app: build-test-image
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: build-image
          image: gcr.io/kaniko-project/executor:v0.16.0
          args: ["--context=git://github.com/rkamradt/hellok8s.git#refs/heads/master",
                  "--dockerfile=DockerfileHelloworldTest",
                  "--verbosity=debug",
                  "--cache=true",
                  "--insecure=true",
                  "--destination=registry.container-registry:5000/helloworldtest:latest"]
