apiVersion: batch/v1
kind: Job
metadata:
  name: nodekube
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 2400 # time to allow job to run
  template:
    metadata:
      labels:
        app: nodekube
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: nodekube
          image: localhost:32000/nodekube:latest
          volumeMounts:
          - mountPath: /root
            name: root-volume
      volumes:
      - name: root-volume
        hostPath:
          path: /home/rkamradt
