apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 2400 # time to allow job to run
  template:
    metadata:
      labels:
        app: test
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: test
          image: localhost:32000/helloworldtest:latest
          env:
           - name: HELLO_URL
             value: "http://test-service"
